DROP DATABASE IF EXISTS MAILDB;

CREATE DATABASE MAILDB;

USE MAILDB;

DROP TABLE IF IT EXISTS MAILMESSAGE;
DROP TABLE IF IT EXISTS RECIPIENT;
DROP TABLE IF IT EXISTS ATTACHMENT;
DROP TABLE IF IT EXISTS FOLDER;


CREATE TABLE MAILMESSAGE(
	MAIL_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FROM_FIELD VARCHAR(50) NOT NULL DEFAULT '',
	SUBJECT VARCHAR(50) NOT NULL DEFAULT '',
	TEXT MEDIUMTEXT NOT NULL DEFAULT '',
	HTML MEDIUMTEXT,
	SENT_DATE TIMESTAMP DEFAULT NULL,
	RECEIVE_DATE TIMESTAMP DEFAULT NULL,
	FOLDER INT NOT NULL,
	MAILSTATUS INT NOT NULL
)

CREATE TABLE ATTACHMENT(
	ATTACH_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

)