DROP DATABASE IF EXISTS MAILDB;

CREATE DATABASE MAILDB;

USE MAILDB;

DROP TABLE IF IT EXISTS MAILMESSAGE;
DROP TABLE IF IT EXISTS RECIPIENT;
DROP TABLE IF IT EXISTS ATTACHMENT;
DROP TABLE IF IT EXISTS FOLDER;


CREATE TABLE MAILMESSAGE(
	MAIL_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FROM_FIELD VARCHAR(50) NOT NULL DEFAULT '',
	SUBJECT VARCHAR(50) NOT NULL DEFAULT '',
	TEXT MEDIUMTEXT NOT NULL DEFAULT '',
	HTML MEDIUMTEXT,
	SENT_DATE TIMESTAMP DEFAULT NULL,
	RECEIVE_DATE TIMESTAMP DEFAULT NULL,
	FOLDER INT NOT NULL,
	MAIL_STATUS INT NOT NULL
)

CREATE TABLE RECIPIENT(
	RECIPIENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ADDRESS VARCHAR(30) NOT NULL,
	ADDRESS_TYPE VARCHAR(10)
	EMAIL_ID INT NOT NULL
)

CREATE TABLE ATTACHMENT(
	ATTACH_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CONTENT_ID VARCHAR(50),
	NAME VARCHAR(30) NOT NULL,
	SIZE INT NOT NULL,
	CONTENT MEDIUMBLOB NOT NULL,
	EMAIL_ID INT NOT NULL
)

